name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.local/state/cabal
          key: cabal-global

      - uses: actions/cache@v4
        with:
         path: dist-newstyle
         key: cabal-local

      - run: cabal update
      - run: cabal test
